name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test-client:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    
    - name: Install dependencies
      working-directory: ./client
      run: npm ci
    
    - name: Lint client code
      working-directory: ./client
      run: npm run lint || echo "Linting issues found"
    
    - name: Run client tests
      working-directory: ./client
      run: npm test -- --passWithNoTests
  
  lint-and-test-server:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_autism_pathways
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      working-directory: ./server
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint server code
      working-directory: ./server
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "Linting issues found"
    
    - name: Run server tests
      working-directory: ./server
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_autism_pathways
        SECRET_KEY: test_secret_key
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'dummy-key-for-testing' }}
      run: pytest -xvs || echo "Tests failed"
  
  build-docker-images:
    runs-on: ubuntu-latest
    needs: [lint-and-test-client, lint-and-test-server]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build client Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./client
        push: false
        tags: autism-pathways-client:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build server Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./server
        push: false
        tags: autism-pathways-server:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Uncomment when ready to deploy
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-docker-images
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - name: Deploy to production
  #     run: echo "Deployment would happen here" 